services:
  next-todo-db:
    image: postgres:18
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: next_todo_user
      POSTGRES_PASSWORD: next_todo_pass
      POSTGRES_DB: next_todo
    volumes:
      - next_todo_vol:/var/lib/postgresql

volumes:
  next_todo_vol:
